name: Deploy app and infra

on:
  workflow_dispatch:

jobs:
  deploy_west_infra:
    name: Deploy DR Infra
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    - name: Terraform Init
      id: init
      run: |
        cd infrastructure/us-west-2
        terraform init -input=false
    - name: Terraform Apply
      run: |
        cd infrastructure/us-west-2
        terraform apply --auto-approve -input=false
  deploy_east_infra:
    name: Deploy Main Infra
    runs-on: ubuntu-latest
    timeout-minutes: 1
    needs: deploy_west_infra
    if: always()
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    - name: Terraform Init
      id: init
      run: |
        cd infrastructure/us-east-1
        terraform init -input=false
    - name: Terraform Apply
      run: |
        cd infrastructure/us-east-1
        terraform apply --auto-approve -input=false
  
  